# Generated by Django 5.0.7 on 2024-07-11 18:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_rename_status_ibu_registereduser_jenis_kelamin_bayi_and_more'),
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=300)),
                ('detail', models.TextField()),
                ('penyelenggara', models.CharField(max_length=300)),
                ('lokasi', models.TextField()),
                ('tanggal_waktu_mulai', models.DateTimeField()),
                ('tanggal_waktu_selesai', models.DateTimeField()),
                ('link_event', models.URLField(blank=True, null=True)),
                ('nama_contact_person', models.CharField(blank=True, max_length=50, null=True)),
                ('nomor_contact_person', models.CharField(blank=True, max_length=20, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.registereduser')),
            ],
        ),
        migrations.CreateModel(
            name='PesertaEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peserta', models.CharField(max_length=50)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forum.event')),
            ],
        ),
    ]
