# Generated by Django 5.0.7 on 2024-07-11 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_event_pesertaevent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='tanggal_waktu_mulai',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='tanggal_waktu_selesai',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
