# Generated by Django 5.0.7 on 2024-07-12 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_alter_discussion_title'),
        ('forum', '0003_alter_event_tanggal_waktu_mulai_and_more'),
    ]

    operations = [
    ]
