# Generated by Django 5.0.7 on 2024-07-11 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registereduser',
            old_name='status_ibu',
            new_name='jenis_kelamin_bayi',
        ),
        migrations.AddField(
            model_name='registereduser',
            name='kondisi_ibu',
            field=models.CharField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='registereduser',
            name='umur_bayi',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='registereduser',
            name='golongan_darah',
            field=models.CharField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='registereduser',
            name='umur',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.DeleteModel(
            name='Bayi',
        ),
    ]
