# Generated by Django 5.0.7 on 2024-07-11 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_rename_status_ibu_registereduser_jenis_kelamin_bayi_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registereduser',
            name='agama',
            field=models.CharField(blank=True, default=None, null=True),
        ),
    ]
